name: Release
on: [workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    environment:
      name: pypi
      url: https://pypi.org/p/codelimit
    permissions:
      id-token: write
      contents: write
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 'Set up Poetry'
      uses: snok/install-poetry@v1
    - name: 'Install dependencies'
      run: poetry install --no-interaction --no-root
    - name: 'Python Semantic Release'
      id: release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Update checkout'
      run: |
        git pull
      if: steps.release.outputs.released == 'true'
    - name: 'Build distribution'
      run: poetry build
    - name: 'Publish to PyPI'
      uses: pypa/gh-action-pypi-publish@release/v1
      if: steps.release.outputs.released == 'true'
    - name: 'Update files'
      uses: MathieuSoysal/file-updater-for-release@v1.0.1
      with:
        files: README.md
        prefix: 'rev: '
        with-checkout: false
        version: {{ steps.release.outputs.version }}
    - name: 'Commit GitHub Action distribution'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m 'Update files' || true
